sudo: required
dist: trusty
language: python

matrix:
    include:
        - python: 3.6
          env: KERAS_VERSION=2.2.4
        - python: 3.6
          env: SM_FRAMEWORK='tf.keras'

git:
  submodules: true


install:
  # code below is taken from http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest pandas
  - source activate test-environment
  - pip install --only-binary=numpy,scipy numpy nose scipy matplotlib h5py theano


  # set library path
  - export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib/:$LD_LIBRARY_PATH
  - conda install mkl mkl-service

  # install TensorFlow (CPU version).
  - pip install tensorflow==1.14

  # install keras
  - if [ -z $KERAS_VERSION ]; then
      echo "Using tf.keras";
    else
      echo "Using keras";
      pip install keras==$KERAS_VERSION;
    fi

  # install lib in develop mode
  - pip install -e .[tests]

  # detect one of markdown files is changed or not
  - export DOC_ONLY_CHANGED=False;
  - if [ $(git diff --name-only HEAD~1 | wc -l) == "1" ] && [[ "$(git diff --name-only HEAD~1)" == *"md" ]]; then
      export DOC_ONLY_CHANGED=True;
    fi

# command to run tests
script:
  - export MKL_THREADING_LAYER="GNU"
  - mkdir -p ~/.keras/models
  # set up keras backend
  - if [[ "$DOC_ONLY_CHANGED" == "False" ]]; then
        PYTHONPATH=$PWD:$PYTHONPATH py.test tests/;
    fi

deploy:
  provider: pypi
  user: qubvel
  password:
    secure: QA/UJmkXGlXy/6C8X0E/bPf4izu3rJsztaEmqIM1npxPiv2Uf4WFs43vxkMXwfHrflocdfw8SBM8bWnbunGT2SvDdo/MMCMpol7unE74T/RbODYl6aiJWVM3QKOXL8pQD0oQ+03L1YK3nCeSQdePINEPmuFmvwyO40q8Dwv8HBZIGZlEo4SK4xr8ekxfmtbezxQ7vUL3sNcvCJDXrZX/4UdXrhdRk+zYoN3dv8NmM4FmChajq/m5Am9OPdbdUBHmIYmvk7L3IpwJeMMpG5FVdGNVwYj7XNHlcy+KZ2/CKn9EpslRDPxY4650654PmhSZWDctZG7jiFWLCZBUvowiyAOPZknZNgdu5gJAfdg37XS9IP3HgTZN6Jb5Bm0by3IlKt+dTzyJQcUnRql5B1wwEI0XO3/YWQe1GQQphIO1bli9hT8n8xNDNjc49vDlu4zKyaYnQmLhqNxkyeruXSTpc8qTITuS+EGgkAUrrBj/IaFcutIg9WOzvJ3nZO8X8UG7LlyQx4AOpfHP6bynAmlT+UFccCEq66Zoh7teWLk0lUekuYST2iQJ3pwFoQGYJRCsmxsz7J0B9ayFVVT/fg+GZpZm1oTnnJ27hh8LZWv/Cr/WHOBYc3qvigWx4pDssJ+O6z7de3aWrGvzAVgXr190fRdP55a34HhNbiKZ0YWmrTs=
  on:
    tags: true
  skip_existing: true
  distributions: "sdist bdist_wheel"
